### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by accopeland** [pirovc/ganon#10]
Hi,

python-3.5 is listed as a requirement, but I get the following syntax error(s) 

```
> python --version
Python 3.5.5 :: Anaconda custom (64-bit)

> ./TaxSBP.py create --sorted-output -f t_tmp/acc_len_taxid.txt -n t_tmp/nodes.dmp -m t_tmp/merged.dmp -l 10000000 -r taxid
  File "./TaxSBP.py", line 254
    ret.append((sum_length,*ids))
                              ^
SyntaxError: can use starred expression only as assignment target
```

**Comment by pirovc** [comment]
Hi,

Internally, ganon calls python3 not python to execute TaxSBP. Can you check which version is called when you type `python3 --version`?

Vitor

**Comment by accopeland** [comment]
Hi,

Here's what I find when running in the taxsbp directory

>  python3 TaxSBP.py create -f acc_len_txid.txt -n nodes.dmp -m merged.dmp -s 1 -b 20 > bins.txt
  File "TaxSBP.py", line 254
    ret.append((sum_length,*ids))
                              ^
SyntaxError: can use starred expression only as assignment target

taxsbp> python3 --version
Python 3.4.5

Alex

**Comment by pirovc** [comment]
Hi Alex,

I'll fix that in the next release. If you edit the [line 95 of the ganon file](https://github.com/pirovc/ganon/blob/a26eaca028214b9fbef1ccd4af9f47dd912cfcd7/ganon#L95) and change python3 to python the tool should work fine.

Vitor
