### ISSUE TITLE
Use of --input-directory still results in `Argument list too long`

### ISSUE THREAD

**Issue by dparks1134** [pirovc/ganon#104]
Hello,

I tried to build a database using the --input-directory and --input-extension option.It looks like the script is still expanding this out and trying to run all genomes via a shell command resulting in:

`OSError: [Errno 7] Argument list too long: '/bin/sh'`

Cheers,
Donovan

**Comment by pirovc** [comment]
Hi @dparks1134 

Could you please provide the command line used?

Best
Vitor

**Comment by dparks1134** [comment]
Hi,

I ended up concatenating all the files and using the `--input-files` parameter, but the command that failed was:
`ganon build -d ganon_db --input-directory ./genomes --input-extension .gz --taxdump-file nodes.dmp names.dmp merged.dmp -t 48`

**Comment by YaohuaYangVEC** [comment]
Hi Vitor,
I met the same problem with Donovan. Have you fixed this bug? If not, would you indicate whether the solution Donovan used, concatenating all the files, is correct?
Thanks!
Yaohua

**Comment by pirovc** [comment]
@YaohuaYangVEC 

Yes, I identified the bug and it will be fixed on the next release, hopefully still this year. For now merging the files should work just fine and provide the same results.

Best
Vitor

**Comment by YaohuaYangVEC** [comment]
> @YaohuaYangVEC
> 
> Yes, I identified the bug and it will be fixed on the next release, hopefully still this year. For now merging the files should work just fine and provide the same results.
> 
> Best
> Vitor

Thanks for this clarification, Vitor!
Yaohua

**Comment by pirovc** [comment]
Fixed #110
