### ISSUE TITLE
Reporting of subspecies/strain

### ISSUE THREAD

**Issue by dparks1134** [pirovc/ganon#112]
Hi,

The CLI of `ganon classify` indicates it will report results at species+. I took this to mean subspecies/strains as defined by the NCBI Taxonomy. However, I have yet to observe classifications below the rank of species even on trivial test sets (e.g. simulated reads from a subspecies/strain in the reference database). Personally, I think this is fine, but I just wanted to confirm that ganon doesn't reporting subspecies/strains.

Cheers,
Donovan

**Comment by pirovc** [comment]
Hi Donovan,

It depends on how you built the database with `ganon build` parameter `-r/--rank`. The default is set to species, meaning you won't have species+/subspecies/strains and all assignments are species or higher. 

If you build the ganon database with `-r taxid` ganon will consider all taxonomic nodes of the NCBI Taxonomy and will include all nodes descendants from species nodes (all leaf nodes, mainly subspecies and no_rank). In this case you will have subspecies/strains in the classification. If you want to go further you can also `-r assembly` to get assembly level classifications.

The species+ is just a grouping rank that collects all those undefined nodes after species (https://www.biorxiv.org/content/biorxiv/early/2019/09/16/406017/F2.large.jpg -> nodes with an X are the taxids nodes). NCBI does not provide taxids for strains anymore, so this is kept to maintain compatibility with older entries and still use some of those subspecies classification that can be informative for some.

Best
Vitor

**Comment by dparks1134** [comment]
Thanks Vitor. Makes perfect sense.
