### ISSUE TITLE
question about output files of ganon 0.1.5.

### ISSUE THREAD

**Issue by margeti** [pirovc/ganon#117]
Could it be that the descriptions of the output files in this github are not valid for the output files generated with the version 0.1.5.? There is no .all file, instead a .out file and the .rep file has way to many columns for the description given .... is there any updated description available? 
Thanks in advance!

**Comment by pirovc** [comment]
Hi @margeti 

Indeed, the output has changed in the current version. To see the specifications and outputs for version 0.1.5 please check the README here: https://github.com/pirovc/ganon/tree/v0.1.5

I highly encourage to use the latest version which has many performance improvements and bug fixes. If you have databases created with the version 0.1.5 please use the following script to covert them to the new standard: https://github.com/pirovc/ganon/blob/master/scripts/convert-db-0.1-0.2.py

Best
Vitor

**Comment by margeti** [comment]
Thanks! I thought there should be somewhere this description, but just couldn't find it.. thank you for this quick reply and I will try to switch to the newest version!

**Comment by pirovc** [comment]
Sure, feel free to re-open the issue if you have any problems.
