### ISSUE TITLE
GTDB

### ISSUE THREAD

**Issue by andrewjmc** [pirovc/ganon#140]
Any experiences/suggestions for using Ganon with GTDB? There seem to be great advantages of GTDB for taxonomic assignment!

Thanks.

**Comment by pirovc** [comment]
Hi @andrewjmc 

I did some experiments using GTDB+ganon and I also think it bring great advantages for some applications. GTDB integration is on the top list of next implementations for ganon but there is no estimation when it will be available.

If you think about trying it manually, one could translate the GTDB taxonomy to the same format of the NCBI taxonomy (`nodes.dmp` and `names.dmp`) They should be provided to `ganon build` with `--taxdump-file nodes.dmp names.dmp`. Further, the linking of the taxonomy and the sequences should also be given with the `--seq-info-file`. Ganon treat taxids as string so no need to convert them to a numeric format.

I'll mark this as an enhancement and hope to add the support to the GTDB soon.

Best
Vitor

**Comment by pirovc** [comment]
It is also important that the root node taxid in the nodes.dmp file is assigned to "1", so the algorithm can parse the custom taxonomy properly.

Vitor

**Comment by andrewjmc** [comment]
Great, thanks. Sounds like a fun project to try!

**Comment by andrewjmc** [comment]
Page 40 of the mmseqs manual looks like it shows making nodes.dmp, names.dmp and makes a mapping file (accession and taxid). Does that sound good?

**Comment by pirovc** [comment]
Sounds good, let me know if something does not work as expected or if you need some more information.

**Comment by andrewjmc** [comment]
Update: making progress with using `flextaxd` with walkthrough that the author made (https://github.com/FOI-Bioinformatics/flextaxd/wiki/Walkthrough---merge-NCBI-with-GTDB`). This has the beauty of allowing me to keep the NCBI virus and fungal taxonomy.

Hitting a problem because many GTDB genomes have contigs called `>contig_N` and ganon complains the names are non-unique. I have raised this as an issue with flextaxd (https://github.com/FOI-Bioinformatics/flextaxd/issues/22), suggesting that GCA/GCF names be prepended when this is detected.

Not sure if the problem would also be encountered when building in a more standard way with ganon, but worth a heads up!

**Comment by pirovc** [comment]
Interesting approach with the `flextaxd` to merge taxonomies, thanks for sharing.
Indeed, ganon (and the clustering with taxsbp) rely on unique sequence identifiers to properly track the files and will ignore those repeated entries.
Looking forward to see the advances. Let me know if something else is fails, should be easier for me to track down the problem.

Cheers

**Comment by davve2** [comment]
The latest release deals with duplicated headers

https://github.com/FOI-Bioinformatics/flextaxd/releases/tag/v0.3.2

**Comment by pirovc** [comment]
GDTB is now natively supported with ganon v1.2.0 #217
