### ISSUE TITLE
Peak memory usage of ganon build

### ISSUE THREAD

**Issue by andrewjmc** [pirovc/ganon#148]
How do I estimate RAM usage of ganon build? And how do I control it?

I keep getting `bad_alloc`s. I have 100 Gb RAM. Fasta file is 36 Gb gzipped (human, RefSeq viruses and fungi, GTDB representative archaea and bacteria). Formal count (seqkit) says 127 billion bases.

```
Parsing taxonomy
 - done in 0.40s.

Extracting sequence identifiers
 - 3426349 entries in the --seq-info-file
 - done in 2.38s.

Build: adding 3426085 sequences

Calculating best bin length
 - Approx. min. size possible: 100974.06MB
 - bin length: 2522550bp (approx: 75825 bins / 148893.99MB)
 - done in 39.76s.

Running taxonomic clustering (TaxSBP)
 - 75903 bins created
 - done in 98.11s.

Building database files
 - ncbi_human_virus_gtdb_bacteria_archaea_ganon.map
 - ncbi_human_virus_gtdb_bacteria_archaea_ganon.tax
 - ncbi_human_virus_gtdb_bacteria_archaea_ganon.gnn
 - done in 39.96s.

Building index (ganon-build)
 - max unique 19-mers: 2522532
 - IBF calculated size with fp<=0.05: 149019.62MB (16469055 bits/bin * 75904 optimal bins [75903 real bins])
The following command failed to run:
/rds/general/user/ajm3018/home/anaconda3/envs/ganon/bin/ganon-build --seqid-bin-file ncbi_human_virus_gtdb_bacteria_archaea_ganon_tmp/acc_bin.txt --filter-size-bits 1250067150720 --kmer-size 19 --hash-functions 3 --threads 48 --output-filter-file ncbi_human_virus_gtdb_bacteria_archaea_ganon.ibf     --reference-files ncbi_human_virus_gtdb_bacteria_archaea_ganon/library.fasta.gz

Error code: -6
Out:
Error:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

I tried to reduce `max-bloom-size` to 100 Gb, but ganon complained this was too small for the specified false positive rate.

Thanks!

**Comment by pirovc** [comment]
Hi @andrewjmc 

You are right with the `max-bloom-size`, that's the way to control it but it seems like you really reached the limit with your parameters.  Right at the beginning ganon shows the approximate minimum memory necessary with the parameters given:

```
Calculating best bin length
 - Approx. min. size possible: 100974.06MB
```

You can try to increase the min. false positive rate (which is very conservative at 0.05) or reduce the number of hash functions (to  2 for example) or increase the k-mer size. However those parameters do not affect the size so much.

Another idea is to remove redundancy of your references by keeping top assemblies for each taxonomic groups if that is the case for your data.

Another work around is to create separated databases for each organisms group, for example: one virus, one human, one bacteria, one archaea. When you use ganon classify you can provide them in hierarchical levels so they won't be loaded at the same time in memory.

All those workarounds will affect your results somehow.

Cheers
Vitor

**Comment by andrewjmc** [comment]
OK, that's good news overall as we're not far above 100 Gb!

**Comment by pirovc** [comment]
@dcrp1234 hi! please take a look at some strategies listed here (they also apply to reduce memory usage): https://pirovc.github.io/ganon/default_databases/#reducing-database-size

The easy solution is to use `--filter-type ibf --filter-size 250000` but I highly recommend to try to use the `--filter-type hibf` (already the default) with a slightly higher `--max-fp` (e.g `0.003`) to get the advantages of the HIBF filter introduced in ganon2. However, if this also fails it will require some trial and error. It's not possible to directly tell how much memory you'll need since this is based on the uniqueness of the k-mers in the reference genomes being used.

**Comment by dcrp1234** [comment]
Hi, 

It seemed to be a network filesystem issue with large IO read/write, running it locally helped.  It was taking 5+ days with 2 threads and 250G memory, I also used --max-fp 0.005, that might have helped too
