### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by davve2** [pirovc/ganon#159]
Hej I got ganon to work for smaller datasaets, but when I try to run a larget set of genomes I get the error pasted below, however it doesn´t give me much information so I can´t begin to debug the error message! If I use exactly the same setup, but limits the number of genomes it runs smoothly.

(Running without verbose)
Error code: -11
Out:
Error:

(Running with verbose)
miniconda3/envs/flextaxd/bin/ganon-build --seqid-bin-file ganon_databases/NCBI_standard_bugtest/_tmp/acc_bin.txt --filter-size-bits 4260405324672 --kmer-size 19 --hash-functions 3 --threads 30 --output-filter-file ganon_databases/NCBI_standard_bugtest/.ibf     --reference-files ganon_databases/NCBI_standard_bugtest/.tmp0.fasta,ganon_databases/NCBI_standard_bugtest/.tmp1.fasta,ganon_databases/NCBI_standard_bugtest/.tmp2.fasta,ganon_databases/NCBI_standard_bugtest/.tmp3.fasta,ganon_databases/NCBI_standard_bugtest/.tmp4.fasta,ganon_databases/NCBI_standard_bugtest/.tmp5.fasta,ganon_databases/NCBI_standard_bugtest/.tmp6.fasta,ganon_databases/NCBI_standard_bugtest/.tmp7.fasta,ganon_databases/NCBI_standard_bugtest/.tmp8.fasta,ganon_databases/NCBI_standard_bugtest/.tmp9.fasta,ganon_databases/NCBI_standard_bugtest/.tmp10.fasta,ganon_databases/NCBI_standard_bugtest/.tmp11.fasta,ganon_databases/NCBI_standard_bugtest/.tmp12.fasta,ganon_databases/NCBI_standard_bugtest/.tmp13.fasta,ganon_databases/NCBI_standard_bugtest/.tmp14.fasta,ganon_databases/NCBI_standard_bugtest/.tmp15.fasta,ganon_databases/NCBI_standard_bugtest/.tmp16.fasta,ganon_databases/NCBI_standard_bugtest/.tmp17.fasta,ganon_databases/NCBI_standard_bugtest/.tmp18.fasta,ganon_databases/NCBI_standard_bugtest/.tmp19.fasta,ganon_databases/NCBI_standard_bugtest/.tmp20.fasta,ganon_databases/NCBI_standard_bugtest/.tmp21.fasta,ganon_databases/NCBI_standard_bugtest/.tmp22.fasta,ganon_databases/NCBI_standard_bugtest/.tmp23.fasta,ganon_databases/NCBI_standard_bugtest/.tmp24.fasta,ganon_databases/NCBI_standard_bugtest/.tmp25.fasta,ganon_databases/NCBI_standard_bugtest/.tmp26.fasta,ganon_databases/NCBI_standard_bugtest/.tmp27.fasta,ganon_databases/NCBI_standard_bugtest/.tmp28.fasta,ganon_databases/NCBI_standard_bugtest/.tmp29.fasta --verbose 2>&1 > ganono-build_log.txt
----------------------------------------------------------------------
--reference-files
                      ganon_databases/NCBI_standard_bugtest/.tmp0.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp1.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp2.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp3.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp4.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp5.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp6.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp7.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp8.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp9.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp10.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp11.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp12.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp13.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp14.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp15.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp16.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp17.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp18.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp19.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp20.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp21.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp22.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp23.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp24.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp25.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp26.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp27.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp28.fasta
                      ganon_databases/NCBI_standard_bugtest/.tmp29.fasta
--seqid-bin-file      ganon_databases/NCBI_standard_bugtest/_tmp/acc_bin.txt
--output-filter-file  ganon_databases/NCBI_standard_bugtest/.ibf
--update-filter-file
--update-complete     0
--filter-size         507879
--filter-size-bits    4260405324672
--hash-functions      3
--kmer-size           19
--threads             30
--n-refs              400
--n-batches           1000
--verbose             1
--quiet               0
----------------------------------------------------------------------
WARNING: sequence not defined on seqid-bin-file [NZ_CP054027.1_GCF_005862185.2]
WARNING: sequence not defined on seqid-bin-file [NZ_CP054028.1_GCF_005862185.2]
WARNING: sequence not defined on seqid-bin-file [NZ_CP054029.1_GCF_005862185.2]
WARNING: sequence not defined on seqid-bin-file [NZ_CP054029.1_GCF_005862185.2]
WARNING: sequence not defined on seqid-bin-file [NZ_CP047412.1_GCF_013487885.1]
WARNING: sequence not defined on seqid-bin-file [NZ_CP047413.1_GCF_013487885.1]
WARNING: sequence not defined on seqid-bin-file [NZ_CP047413.1_GCF_013487885.1]
WARNING: sequence not defined on seqid-bin-file [NZ_CP047416.1_GCF_013487925.1]
WARNING: sequence not defined on seqid-bin-file [NZ_CP047416.1_GCF_013487925.1]
WARNING: sequence not defined on seqid-bin-file [NZ_CP045506.1_GCF_013376495.1]
WARNING: sequence not defined on seqid-bin-file [NZ_CP045506.1_GCF_013376495.1]
Segmentation fault

**Comment by pirovc** [comment]
Hi @davve2 

Could you please paste the `ganon build` command used and tell me which ganon version are you running?

I can see many suspicious things: 
 - do you have around 500GB on the machine running this command?
 - It looks like your --db-prefix is a folder (`ganon_databases/NCBI_standard_bugtest/`) instead of `ganon_databases/NCBI_standard_bugtest/FILENAME` and this can be causing issues. 
 - the headers seem to be customized (NZ_CP054027.1_GCF_005862185.2). Did you create the --seq-info-file manually?

**Comment by davve2** [comment]
Thanks for a quick answer!

The command would be:
```ganon build -d ganon_databases/NCBI_standard_bugtest/ --verbose --seq-info-file custom.seq2id -t 30 --taxdump-file nodes.dmp names.dmp -i ganon_databases/NCBI_standard_bugtest/.tmp0.fasta```

```version: ganon 0.3.3```

tmp0.fasta is actually a list of tmp fasta files (same number as threads) separated with comma according to the manual


It works perfectly for a smaller databases (also with custom headers) with an identical command.

* I have 756GB RAM so that should be ok!
* I suppose the trailing / may cause the problem? but it does work for smaller databases!
* Yes they are customized (related to the GTDB issue #140 ) and I´m giving a custom --seq-info-file

**Comment by pirovc** [comment]
You can use a folder as `--db-prefix` but the files will be nameless (e.g. `ganon_databases/NCBI_standard_bugtest/.ibf, ganon_databases/NCBI_standard_bugtest/.tax, ...`) inside the folder. I tested and it works so the problem is not here.

Not sure how it worked before, but the input of `ganon build` is always space separated and it does not work here for comma separated files.

> tmp0.fasta is actually a list of tmp fasta files (same number as threads) separated with comma according to the manual

Not sure what do you mean by that. Is `tmp0.fasta` a file listing the other files? ganon does not support this input mode.

**Comment by davve2** [comment]
That is true, this is what happens to me the database files are nameless!

Yes you are correct, I am the one mixing up things here here. I separate my input ```-i```to ganon build by space not comma. It was the internal ```ganon-build``` command  from the teminal output where the parameter ```--reference-files``` show my input files separated by comma (which is why I wrongly assumed I also gave them separated by comma). I give a range of fasta files, same as the number of threads.

like ```-i tmp0.fasta tmp1.fasta tmp2.fasta... tmp[nthreads].fasta``` will be sent as input.

**Comment by pirovc** [comment]
Segfault is always unexpected. If you compile ganon manually, you can build the c++ with `-DCMAKE_BUILD_TYPE=Debug` (https://github.com/pirovc/ganon#downloading-and-building-ganon) and post here the output but I can help to further investigate the issue before that.

Could you send me the header of the files: `ganon_databases/NCBI_standard_bugtest/_tmp/acc_bin.txt` and `custom.seq2id` and some headers (">...") of your fasta files?

Is the bug happening early or later in the run? could you please try again with `/usr/bin/time -v ganon build ...` and paste the output here?

Another thing: not sure why you are splitting your fasta files in the same number of threads. Ganon does not use one file per thread but automatically distribute sequences among threads, so you can just use a single fasta file and get the same performance. I can imagine that maybe something is going wrong when splitting those files and causing the error.

**Comment by davve2** [comment]
Ok great thanks!

I´ll get back to you with a proper time output, I have a meeting now!

However, It happens about 12 minutes into the process most likely after the index build

```Building index (ganon-build)
 - max unique 19-mers: 16999510
 - IBF calculated size with fp<=0.05: 480110.84MB (110986046 bits/bin * 36288 optimal bins [36250 real bins])
The following command failed to run:
```  
See more detail in the first post

Fasta header examples
``` 
>NC_042506.1_GCF_003054445.1
>NC_042507.1_GCF_003054445.1
>NC_042508.1_GCF_003054445.1
>NC_042509.1_GCF_003054445.1
>NC_042509.1_GCF_003054445.1
>NC_031672.1_GCF_001640025.1
>NC_031674.1_GCF_001640025.1
>NC_031671.1_GCF_001640025.1
>NC_031671.1_GCF_001640025.1
>NC_036025.1_GCF_001417885.1
```

tail of acc_bin.txt
```
NZ_HG322956.1_GCF_000455325.1   1       6569    36247
NZ_HG322955.1_GCF_000455325.1   1       22117   36247
NZ_HG322952.1_GCF_000455325.1   1       1475816 36247
NZ_HG322957.1_GCF_000455325.1   1       5316    36247
NZ_HG322954.1_GCF_000455325.1   1       223858  36247
NZ_HG322953.1_GCF_000455325.1   1       965587  36247
NZ_HG322951.1_GCF_000455325.1   1       4209572 36247
NC_043472.1_GCF_003673625.1     1       7152    36248
NC_043473.1_GCF_003673625.1     1       4788    36248
NC_029099.1_GCF_001550825.1     1       49797   36249
```

head of seqid2taxid.map
```
NC_042506.1_GCF_003054445.1     2852272 4909
NC_042507.1_GCF_003054445.1     2745854 4909
NC_042508.1_GCF_003054445.1     2541747 4909
NC_042509.1_GCF_003054445.1     1383544 4909
NC_042510.1_GCF_003054445.1     1289138 4909
NC_031672.1_GCF_001640025.1     5930846 796027
NC_031674.1_GCF_001640025.1     4956242 796027
NC_031671.1_GCF_001640025.1     2773601 796027
NC_031673.1_GCF_001640025.1     2277569 796027
NC_036025.1_GCF_001417885.1     1745387 1003335
```

**Comment by davve2** [comment]
Running the build command in the terminal (not through a subprocess) I got this message now, but I+m not sure what it means

Command (minus 49 fasta files)
```
/usr/bin/time -v ganon build -d  ganon_databases/NCBI_standard_bugtest_refseq2 --seq-info-file databases/taxonomy/ganon/NCBI_base_202011_annot/seqid2taxid.map --taxdump-file ganon_databases/NCBI_standard_bugtest_refseq2/taxonomy/names.dmp ganon_databases/NCBI_standard_bugtest_refseq2/taxonomy/nodes.dmp --verbose -t 50 -i ganon_databases/NCBI_standard_bugtest_refseq2/.tmp0.fasta
```

```
Traceback (most recent call last):
  File "/home/davsun/miniconda3/envs/flextaxd/bin/ganon", line 33, in <module>
    sys.exit(load_entry_point('ganon==0.3.3', 'console_scripts', 'ganon')())
  File "/home/davsun/miniconda3/envs/flextaxd/lib/python3.8/site-packages/ganon/ganon.py", line 48, in main_cli
    sys.exit(0 if main() else 1)
  File "/home/davsun/miniconda3/envs/flextaxd/lib/python3.8/site-packages/ganon/ganon.py", line 34, in main
    ret=build(cfg)
  File "/home/davsun/miniconda3/envs/flextaxd/lib/python3.8/site-packages/ganon/build_update.py", line 129, in build
    bin_size_bits = math.ceil(-(1/((1-cfg.max_fp**(1/float(cfg.hash_functions)))**(1/float(cfg.hash_functions*max_kmer_count))-1)))
ValueError: cannot convert float NaN to integer
Command exited with non-zero status 1
        Command being timed: "ganon build -d ganon_databases/NCBI_standard_bugtest_refseq2 --seq-info-file databases/taxonomy/ganon/NCBI_base_202011_annot/seqid2taxid.map --taxdump-file ganon_databases/NCBI_standard_bugtest_refseq2/taxonomy/names.dmp ganon_databases/NCBI_standard_bugtest_refseq2/taxonomy/nodes.dmp --verbose -t 50 -i ganon_databases/NCBI_standard_bugtest_refseq2/.tmp0.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp1.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp2.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp3.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp4.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp5.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp6.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp7.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp8.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp9.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp10.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp11.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp12.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp13.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp14.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp15.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp16.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp17.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp18.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp19.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp20.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp21.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp22.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp23.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp24.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp25.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp26.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp27.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp28.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp29.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp30.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp31.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp32.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp33.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp34.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp35.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp36.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp37.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp38.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp39.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp40.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp41.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp42.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp43.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp44.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp45.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp46.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp47.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp48.fasta ganon_databases/NCBI_standard_bugtest_refseq2/.tmp49.fasta"
        User time (seconds): 33.10
        System time (seconds): 6.50
        Percent of CPU this job got: 125%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:31.53
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1664356
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1102318
        Voluntary context switches: 200
        Involuntary context switches: 67
        Swaps: 0
        File system inputs: 64
        File system outputs: 8
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
```

**Comment by pirovc** [comment]
Thanks for sending the files. They look correct.  Another question: is the .ibf file there when the code breaks or not?

Given the time into the build and the type of error I'm guessing that some of your input fasta file is corrupted or has something unexpected and it's breaking the run. Could you try to re-run it with just the first file `.tmp0.fasta` to see what happens?

**Comment by davve2** [comment]
Actually, it seems like it may be on my end the code is breaking, I was just about to send you some test files when I discovered that the first header was missing in the file (and in a few others)! I think this is what is causing the error! I didn´t expect this since it is working from my end on smaller input datasets :/ Perhaps I have some faulty fasta files in my larger set!

I will do some additional bug testing on my side and close the issue if this seems to be the only problem!  Thanks for your help and quick response!

**Comment by pirovc** [comment]
Hi @davve2 I'm glad you found the solution. Could you share what was wrong with the files so I may add an exception to it?

**Comment by davve2** [comment]
Ah yes that would be great!  The problem in the end was that some of the fasta sequences was missing a header, so instead of ```>headername``` the line was blank. The error occured both if the first header was blank or if any subsequent headers were blank later on in the file. I suppose the best option might be to put out a warning that there are emtpy lines, otherwise there is a risk of sequences getting tagged to the wrong taxa without notification. 

I was thinking myself to build (or integrate some existing) fasta validator at least as an option.
