### ISSUE TITLE
[Errno 7] Argument list too long v 0.4.0

### ISSUE THREAD

**Issue by Lucas-Maciel** [pirovc/ganon#167]
Hi, I'm trying to use ganon but I got an error when I tried to  build the dataset

`ganon build --db-prefix ganon_db -t 32 --input-files RefSeqCG_arc_bac/v1/files/*genomic.fna.gz`
- - - - - - - - - -
   _  _  _  _  _   
  (_|(_|| |(_)| |  
   _|   v. 0.4.0
- - - - - - - - - -
Downloading taxdump
 - done in 5.72s.

Unpacking taxdump
 - done in 6.61s.

Parsing taxonomy
 - done in 4.71s.

Extracting sequence identifiers
 - 44723 unique sequence headers successfully retrieved from 21442 input file(s)
 - done in 2417.85s.

Retrieving sequence information from NCBI E-utils
 - 44723 sequences successfully retrieved
 - done in 639.22s.

Build: adding 44723 sequences

Calculating best bin length
 - Approx. min. size possible: 68961.01MB
 - bin length: 11707469bp (approx: 11269 bins / 103218.53MB)
 - done in 6.24s.
Building database files
 - ganon_db.map
 - ganon_db.tax
 - ganon_db.gnn
 - done in 1.00s.

Building index (ganon-build)
 - max unique 19-mers: 11707451
 - IBF calculated size with fp<=0.05: 110799.55MB (76435362 bits/bin * 12160 optimal bins [12144 real bins])
The following command failed to run:
*Huge list of file*
~[Errno 7] Argument list too long: '/lucmac/miniconda3/bin/ganon-build'
Error code: 0
Out: 
Error:

**Comment by pirovc** [comment]
Hi @Lucas-Maciel 

Please check the following parameters:

```
  --input-directory     Directory containing input files
  --input-extension     Extension of files to use with --input-directory (provide it without * expansion, e.g. ".fna.gz")
```

the command would be something like: `ganon build --db-prefix ganon_db -t 32 --input-directory "RefSeqCG_arc_bac/v1/files/" --input-extension "genomic.fna.gz"`

**Comment by Lucas-Maciel** [comment]
@pirovc thanks for you fast reply, but changing the parameters as you suggested got me the same error

`ganon build --db-prefix ganon_db -t 32 --input-directory "RefSeqCG_arc_bac/v1/files/" --input-extension "genomic.fna.gz"`

Building index (ganon-build)
 - max unique 19-mers: 11707451
 - IBF calculated size with fp<=0.05: 110799.55MB (76435362 bits/bin * 12160 optimal bins [12144 real bins])
The following command failed to run:
/lucmac/miniconda3/bin/ganon-build --seqid-bin-file ganon_db_tmp/acc_bin.txt --filter-size-bits 929454001920 --kmer-size 19 --hash-functions 3 --threads 32 --output-filter-file ganon_db.ibf    --reference-files [files] --directory-reference-files RefSeqCG_arc_bac/v1/files/ --extension genomic.fna.gz

[Errno 7] Argument list too long: '/lucmac/miniconda3/bin/ganon-build'
Error code: 0
Out: 
Error:

**Comment by pirovc** [comment]
Thanks for sharing again, there is indeed a bug causing this issue. I will provide a fix very soon.

In the meantime, please just concatenate your files together `cat RefSeqCG_arc_bac/v1/files/*genomic.fna.gz > sequences.fna.gz` and use it directly `ganon build --db-prefix ganon_db -t 32 --input-files sequences.fna.gz`
