### ISSUE TITLE
Building Refseq database fails with a numpy type error

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [pirovc/ganon#168]
Hi,

I am using ganon 0.4.0 and genome_updater 0.2.5 in a clean Conda environment to generate new Ganon reference. After downloading the latest version of Refseq and concatenating the genomes for processing, I get the following Numpy error after running the database build command. I did manually specify python=3.6 in the environment as well.

I can always downgrade to a previous version of Ganon, but given the lack of an outstanding issue I figure it might be something simple to resolve on my end. Any suggestions are appreciated!

Download command:

```
genome_updater.sh -g "archaea,bacteria" \
                  -d "refseq" \
                  -l "Complete Genome" \
                  -f "genomic.fna.gz,assembly_report.txt" \
                  -o "RefSeqCG_arc_bac" -b "v1" \
                  -a -m -u -r -p -t 24
```

Build command:
```
ganon build --db-prefix ganon_db \
            --input-files merged.genomic.fna.gz \
            --seq-info-file RefSeqCG_arc_bac/v1/seqinfo.txt \
            --taxdump-file RefSeqCG_arc_bac/v1/taxdump.tar.gz
```

Stack trace:
```
- - - - - - - - - -
   _  _  _  _  _
  (_|(_|| |(_)| |
   _|   v. 0.4.0
- - - - - - - - - -
Unpacking taxdump
 - done in 1.68s.

Parsing taxonomy
 - done in 5.51s.

Parsing --seq-info-file
 - 45892 unique sequence entries in the --seq-info-file RefSeqCG_arc_bac/v1/seqinfo.txt
 - done in 0.05s.

Build: adding 45892 sequences

  File "/opt/conda/envs/ganon_env/bin/ganon", line 33, in <module>
    sys.exit(load_entry_point('ganon==0.4.0', 'console_scripts', 'ganon')())
  File "/opt/conda/envs/ganon_env/lib/python3.6/site-packages/ganon/ganon.py", line 48, in main_cli
    sys.exit(0 if main() else 1)
  File "/opt/conda/envs/ganon_env/lib/python3.6/site-packages/ganon/ganon.py", line 34, in main
    ret=build(cfg)
  File "/opt/conda/envs/ganon_env/lib/python3.6/site-packages/ganon/build_update.py", line 69, in build
    bin_length, approx_size, n_bins = estimate_bin_len_size(cfg, seqinfo, tax)
  File "/opt/conda/envs/ganon_env/lib/python3.6/site-packages/ganon/build_update.py", line 558, in estimate_bin_len_size
    bin_lens = np.geomspace(min_bin_len, max_bin_len, num=300)
  File "<__array_function__ internals>", line 6, in geomspace
  File "/opt/conda/envs/ganon_env/lib/python3.6/site-packages/numpy/core/function_base.py", line 403, in geomspace
    both_negative = (_nx.sign(start) == -1) & (_nx.sign(stop) == -1)
numpy.core._exceptions.UFuncTypeError: ufunc 'sign' did not contain a loop with signature matching types dtype('<U32') -> dtype('<U32')
```

**Comment by pirovc** [comment]
Hi @jdwinkler-lanzatech 

Everything seems correct and ganon 0.4.0 is supported in py3.6 so I guess is a bug related to the data. Just to be sure, which version of numpy an pandas is installed in your environment?

Could you please share with me your file `RefSeqCG_arc_bac/v1/seqinfo.txt` so I can properly debug it? Should be small when compressed.

**Comment by jdwinkler-lanzatech** [comment]
I actually narrowed it down to a bug in the seqinfo file, since I can omit it from the build command and generate the DB. Could be that the awk example command needs adjusting?

File attached! Let me know if you need any additional information and thanks for the help.
[seqinfo.txt.gz](https://github.com/pirovc/ganon/files/6631598/seqinfo.txt.gz)

**Comment by jdwinkler-lanzatech** [comment]
Tool versions:

```
binpacking      1.4.3
certifi         2021.5.30
future          0.18.2
ganon           0.4.0
numpy           1.19.5
pandas          1.1.5
pip             21.1.2
pylca           1.0.0
python-dateutil 2.8.1
pytz            2021.1
setuptools      49.6.0.post20210108
six             1.16.0
taxsbp          1.1.1
wheel           0.36.2
```

**Comment by pirovc** [comment]
There are some "na" instead of the sequence lengths in your seqinfo.txt causing the trouble `grep "na" seqinfo.txt`. This comes from NCBI in their reports. I will mark this as a bug because ganon should just ignore those entries and not break.

To make it work you can just remove the entries with "na" or replace them with 0 `sed -i 's/na/0/g' seqinfo.txt`

Thanks for reporting and sending the file!

**Comment by jdwinkler-lanzatech** [comment]
That makes sense. I eventually dropped the sequence file input ganon build as a workaround, but I'll purge the NA entries if I need to re-run in the near future. Thanks for the help!
