### ISSUE TITLE
Suggestions on reducing DB size?

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [pirovc/ganon#169]
Hi again,

Do you have any suggestions on how to reduce Ganon's database size without giving up too much sensitivity? As RefSeq or other databases continue to grow, it's becoming more I/O and memory demanding to run Ganon. 

The other possible solution I can think of would be breakdown the database into fixed sized chunk that get loaded incrementally. Not sure if that is possible, but might be helpful long term.

**Comment by pirovc** [comment]
Hi @jdwinkler-lanzatech 

We are well aware of the fast data growth on the repositories and alreaday working on improvements to reduce database size in a newer version of the tool. Thanks for the suggestion to work on chunks, we have something planed is this direction. 

For the current ganon version, using only a limited number of references for each taxonomic groups (e.g. species) reduces redundancy, which is plenty on refseq, and achieves almost same results with a much smaller database. This can be easily done with the `-j` function on [genome_updater](https://github.com/pirovc/genome_updater) when downloading sequences. Of course, if the goal is to classify sequences at sequence/strain/assembly level, this would not be recommended.

**Comment by pirovc** [comment]
#187 introduces minimizers, enabling smaller databases with more data. Please give it a try if still on the issue. Will close it for now.
