### ISSUE TITLE
seqan3::parse_error on database build

### ISSUE THREAD

**Issue by bioscienceresearch** [pirovc/ganon#183]
Python 3.8.12
ganon 1.0.0

Building database from NCBI nt database in fasta format (354GB)

Command:

`ganon build --db-prefix nt --input-files nt.fa`

Error trace:

`Building database files
 - nt.map
 - nt.tax
 - nt.gnn
 - done in 12.71s.

Building index (ganon-build)
 - max unique 19-mers: 102541
 - IBF calculated size with fp<=0.05: 5.11MB (669469 bits/bin * 64 optimal bins [42 real bins])
The following command failed to run:
~/envs/taxonomy/bin/ganon-build --seqid-bin-file nt_tmp/acc_bin.txt --bin-size-bits 669469 --kmer-size 19 --hash-functions 3 --threads 2 --output-filter-file nt.ibf     --reference-files nt.fa  

Error code: -6
Out: 
Error: 
terminate called after throwing an instance of 'seqan3::parse_error'
  what():  Encountered an unexpected letter: char_is_valid_for<seqan3::dna15> evaluated to false on 'x'`

**Comment by pirovc** [comment]
It seems like your nt.fa is corrupted or contains some unexpected chars (an `x`?). I tried to run a small example here with the top of the nt (including other chars as ACGTN) and it runs just fine. Also the values calculated by ganon you reported are very far from reality, so something is definitely wrong. I believe you'll need lots of RAM to index the complete nt. Could you double check your nt.fa with the command below and report back?

```bash
# should print one or more lines if some unsupported char is present in the file
sed -n '/^[^>][^ACGTRYSWKMBDHVN]/p' nt.fa
```

**Comment by bioscienceresearch** [comment]
Looks like ganon doesnt likethe use of the 'x' character as a spacer, eg one line of putput from that command:

`xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxAGCTTGCAGAGAGGA`

I can just run a replace, what is the preferred empty/space character used by ganon?

**Comment by pirovc** [comment]
The preferred empty/space char would be N
