### ISSUE TITLE
log files

### ISSUE THREAD

**Issue by rjsorr** [pirovc/ganon#188]
I am running ganon (build at present) through a remote connection to a server so I don't always have possibilty to see the screen log. Sometimes the program exits and as such it is difficult to troubleshoot as to why. Is it possible that the log can be written to a file?

**Comment by pirovc** [comment]
It is actually planned for the next release to have a log file option. For now you can use bash redirection `ganon classify ... > out.log 2>&1` to get everything written into `out.log`

**Comment by rjsorr** [comment]
thanks
