### ISSUE TITLE
Error code1: Please provide a single or one-per-hierarchy --kmer-size value[s]

### ISSUE THREAD

**Issue by rjsorr** [pirovc/ganon#189]
ganon v1.1 

all databases built also with 1.1 and with default settings. so all same k-mers etc. 

ganon build -t 18 -m 275 --db-prefix EUK_refseq_CG_db --input-directory /media/ubuntu/Elements/reference_genomes/genome_updater/euk_refseq_cg/22_12_2021/files --input-extension genomic.fna.gz &

so why am I getting this error and how to fix with the following command: 

for i in *_1_val_1.fq.gz; do
	b=${i%%_1_val_1.fq.gz}
	ganon classify -d /media/ubuntu/Elements/reference_genomes/ganon/ARC_refseq_ALL_db/ARC_refseq_ALL_db \
	/media/ubuntu/Elements/reference_genomes/ganon/BAC_refseq_ALL_db/BAC_refseq_ALL_db \
	/media/ubuntu/Elements/reference_genomes/ganon/EUK_refseq_CG_db/EUK_refseq_CG_db \
	/media/ubuntu/Elements/reference_genomes/ganon/VIRAL_refseq_ALL_db/VIRAL_refseq_ALL_db \
	-p "$b"_1_val_1.fq.gz "$b"_2_val_2.fq.gz \
	-o "$b"_ganon_results --output-lca --output-unclassified -t 16
done &

OUTPUT:
Classifying reads (ganon-classify)
The following command failed to run:
/home/ubuntu/miniconda2/envs/python3.7_environment/bin/ganon-classify  --paired-reads SL335732_1_val_1.fq.gz,SL335732_2_val_2.fq.gz --ibf /media/ubuntu/Elements/reference_genomes/ganon/ARC_refseq_ALL_db/ARC_refseq_ALL_db.ibf,/media/ubuntu/Elements/reference_genomes/ganon/BAC_refseq_ALL_db/BAC_refseq_ALL_db.ibf,/media/ubuntu/Elements/reference_genomes/ganon/EUK_refseq_CG_db/EUK_refseq_CG_db.ibf,/media/ubuntu/Elements/reference_genomes/ganon/VIRAL_refseq_ALL_db/VIRAL_refseq_ALL_db.ibf --map /media/ubuntu/Elements/reference_genomes/ganon/ARC_refseq_ALL_db/ARC_refseq_ALL_db.map,/media/ubuntu/Elements/reference_genomes/ganon/BAC_refseq_ALL_db/BAC_refseq_ALL_db.map,/media/ubuntu/Elements/reference_genomes/ganon/EUK_refseq_CG_db/EUK_refseq_CG_db.map,/media/ubuntu/Elements/reference_genomes/ganon/VIRAL_refseq_ALL_db/VIRAL_refseq_ALL_db.map --tax /media/ubuntu/Elements/reference_genomes/ganon/ARC_refseq_ALL_db/ARC_refseq_ALL_db.tax,/media/ubuntu/Elements/reference_genomes/ganon/BAC_refseq_ALL_db/BAC_refseq_ALL_db.tax,/media/ubuntu/Elements/reference_genomes/ganon/EUK_refseq_CG_db/EUK_refseq_CG_db.tax,/media/ubuntu/Elements/reference_genomes/ganon/VIRAL_refseq_ALL_db/VIRAL_refseq_ALL_db.tax --kmer-size 19,19,19,19 --window-size 0,0,0,0   --rel-cutoff 0.25 --abs-filter 0   --output-prefix SL335732_ganon_results     --threads 16

Error code: 1
Out:
Error:
Please provide a single or one-per-hierarchy --kmer-size value[s]

**Comment by pirovc** [comment]
Hi @rjsorr. Your command call seems to be okay, so it may be just a validation bug, I'm looking into it. Can you re-run it with `--verbose` and paste the output here just to be sure?

**Comment by rjsorr** [comment]
great and cheers!

**Comment by pirovc** [comment]
Bug fixed on version 1.1.1 (#191), soon up in bioconda (https://github.com/bioconda/bioconda-recipes/pull/32484)

**Comment by rjsorr** [comment]
Cheers, when will the update be available through conda?

**Comment by pirovc** [comment]
It's already uploaded it there, so as soon as someone approves and merges it. Keep an eye on https://github.com/bioconda/bioconda-recipes/pull/32484
