### ISSUE TITLE
Functional annotation?

### ISSUE THREAD

**Issue by rjsorr** [pirovc/ganon#197]
Hi, 
I'm wondering as to the possibility of incorporating a functional annotation of reads into ganon, such as that in kraken2?

**Comment by pirovc** [comment]
I was not aware of this function in the kraken2. Could you explain in more detail what do you mean by that?

**Comment by pirovc** [comment]
It's indeed a very interesting use case, but unfortunately out of scope of ganon features at the moment.
However a taxonomic feature will be implemented soon, allowing the use of custom taxonomies which will probably make the re-purposing easier. Thanks for the suggestion.
