### ISSUE TITLE
how to know which reads align to which bins?

### ISSUE THREAD

**Issue by zgzg1197** [pirovc/ganon#206]
I want to know which reads are classified to which species ,can I see the reads alignment infomation?such as the bins ID ,and reads' substring which match the bin?

**Comment by pirovc** [comment]
Not sure if I got what you want but in ganon you get species classification but not the alignment of the read to the specific position. You could also get a classifcation at a more specific level (see [specialization](https://github.com/pirovc/ganon#--specialization)).
