### ISSUE TITLE
Mixing GTDB and NCBI taxonomy

### ISSUE THREAD

**Issue by ohickl** [pirovc/ganon#227]
Hi,
is it possible to mix taxonomy systems when using multiple databases? E.g. id be interested in using GenBank and the latest GTDB release.

Best

Oskar

**Comment by ohickl** [comment]
Thanks for the quick reply!
I wanted to to some kingdom level sorting. But since the eukaryotes are massive and RefSeq only represents a very small (imo skewed) subset, i was planning to build subset databases from the GenBank eukaryotes that individually will fit in ~ 2 tb of memory.
This i would want to pair with the latest 207 GTDB release for the prokaryotes, with which i had pretty good results (at least with kraken2).
As there are some ways to translate GTDB into NCBI, this might be the way to go then? Did not try it tough.

**Comment by pirovc** [comment]
Indeed, would be good to have and it's already a planned feature for multitax which will be ported for `ganon report` but not yet implemented. GTDB to NCBI conversion is quite straightforward. Alternatively, you could build the 207 GTDB genomes with the NCBI taxonomy, so you don't have to translate it at the end.

**Comment by ohickl** [comment]
I will give that a try.
Thanks!

**Comment by shenwei356** [comment]
This may help:

####  Merging GTDB and NCBI taxonomy

- If you need the taxdump files and the `taxid.map` file mapping genome assembly accessions to TaxIds, please follow
  [Merging the GTDB taxonomy (for prokaryotic genomes from GTDB) and NCBI taxonomy (for genomes from NCBI)](https://bioinf.shenwei.me/kmcp/database/#merging-gtdb-and-ncbi-taxonomy).
- If you just need the taxdump files, please follow [Merging GTDB and NCBI taxonomy](https://bioinf.shenwei.me/taxonkit/tutorial/#merging-gtdb-and-ncbi-taxonomy).

**Comment by ohickl** [comment]
Thanks for the tips @shenwei356!
