### ISSUE TITLE
Ganon Bct and Archaea whole genome DB  seems to download fewer files than it should from NCBI 

### ISSUE THREAD

**Issue by shrivaa** [pirovc/ganon#228]
Hi,

I was trying to create a local ganon DB. So, I downloaded the latest assembly, whole genome (top 1), bct and archea database files using ganon, this morning. I got 11,355 files from refseq.

However, there seem to be over 31K reseq files for these in NCBI, in the genbank DB. Any thoughts on what I am missing?

Thank you.

**Comment by pirovc** [comment]
Do you want genomes from refseq only or also genbank? Make sure the `--source` argument is properly set for `ganon build`. Could you share the command used?
