### ISSUE TITLE
conda installed ganon can't use ganon build -g argument?

### ISSUE THREAD

**Issue by LilyAnderssonLee** [pirovc/ganon#252]
Hi, 
I installed ganon through conda and I am having issues to download the databases through this command line. 

`ganon build --organism-group archaea bacteria fungi viral protozoa human --threads 12 --complete-genomes --db-prefix abfcph_refseq_cg`

error message:
`ganon: error: unrecognized arguments: --organism-group archaea bacteria fungi viral protozoa human --complete-genomes
`

I didn't see -g/--organism-group argument in help message of `ganon build -h`
![image](https://github.com/pirovc/ganon/assets/64467552/2766577f-0355-4bae-9544-4a09bf0104a5)

**Comment by pirovc** [comment]
It seems like you are using an outdated ganon version that did not support download of databases directly. Please update it to the latest vesion with `conda update ganon` to have such functionality.

**Comment by LilyAnderssonLee** [comment]
Thanks! My ganon version is 0.2.3 and it seems like I'm unable to update to  the latest version. This could be due to my outdated version of conda. I will get back to you once I've resolved the version issue.

**Comment by LilyAnderssonLee** [comment]
Yeah downloading works now after upgrading the ganon version to 1.6.0. Thanks again.
