### ISSUE TITLE
Error code: -6 The number of hash functions must be > 0 and <= 5

### ISSUE THREAD

**Issue by ksavhughes** [pirovc/ganon#274]
Hi, I got this error message and I'm assuming it is because I set -s 0 to detect the optimal number of hash functions. I'm going to just try using the default (4) value but I wanted to open an issue so you all are aware of this.

**build command:**
ganon build-custom -t 24 -x ncbi --verbose --write-info-file -c -i $db/refs/bacteria3 -d bacteria3 --level species -k 19 -w 31 -s 0 --hibf -p 0.001 --ncbi-file-info $db/refs/assembly_summaries/bacteria3_assembly_summary.txt

**stderr:**
raptor build
terminate called after throwing an instance of 'std::logic_error'
  what():  The number of hash functions must be > 0 and <= 5.
The following command failed to run:
/home/karsav1511/.conda/envs/ganon/bin/raptor build --output 'bacteria3.hibf' --threads 24  --input 'bacteria3_files/build/raptor_layout.binning.out'

Error code: -6

**Comment by pirovc** [comment]
Thanks for reporting. This is not documented properly, but only with `--filter-type ibf` the auto detection works, so for your default use case (`--filter-type hibf`) the n. of hashes has to be set. Either way, this is a bug and will be fixed soon.

**Comment by ksavhughes** [comment]
Oh ok thank you and thanks for the quick response! So do you recommend just using the default number of hashes (4)?

**Comment by pirovc** [comment]
4 is good. The number of hashes will change the size of your database and the classification speed, but classification results should be the same with any value.

**Comment by pirovc** [comment]
Fixed in v2.0.1 #281
