### ISSUE TITLE
version `CXXABI_1.3.11' not found (required by build/ganon-build)

### ISSUE THREAD

**Issue by mdehollander** [pirovc/ganon#52]
While running ganon build I get this error. I am running it within a conda environment with gcc7 installed.

I am using cmake version 3.13.4

**Comment by pirovc** [comment]
Hi @mdehollander 

That's related to the version of your gcc. If you followed the instructions on the readme to use the "conda gcc7" or if you are using an alternative gcc7 version, you'll have to set the LD_LIBRARY_PATH.

`export LD_LIBRARY_PATH=/home/user/miniconda3/envs/gcc7/lib/`

That error won't work in a machine with native gcc7 (at least the ones I tried).

**Comment by mdehollander** [comment]
Awesome. Works now. Thanks.
