### ISSUE TITLE
Nucleotide alphabet

### ISSUE THREAD

**Issue by mat43672** [pirovc/ganon#59]
Hi,

After building a database, smoothly, my run gets stuck on the first "Y" that appears in a read. No error, no crash, cpu usage drops to 0.00% and the task is frozen. 

I use CAMI sets that contain that kind of characters, and were used in your preprint... so before filtering the reads, I just want to be sure there no parameter to deal with this, and can you tell me which alphabet is supported ? ACGTN ...URYSWKMDHV

**Comment by pirovc** [comment]
hi @mat43672 

Indeed the current supported alphabet no is ACGTN and I pre-processed the CAMI data to run on ganon

I will mark it as a bug since it should at least throw an error, or even better, convert unknown bases to N

Best
Vitor

**Comment by mat43672** [comment]
Ok I'll replace anything non supported by N. Yes a message would be welcome.

**Comment by pirovc** [comment]
Solved #103
