### ISSUE TITLE
error message with ganon tests

### ISSUE THREAD

**Issue by fvangef** [pirovc/ganon#61]
(base) fvangef@larix:~/ganon/build$ ./ganon-tests 

--seqid-bin-file      files/bacteria_acc_bin.txt
--output-filter-file  test_output.filter
--filter-size         0
--filter-size-bits    8388352
--hash-functions      3
--kmer-size           19
--n-batches           1000
--n-refs              400
--threads             2
--update-filter-file  
--update-complete     0
--verbose             1
--reference-files     
                      sequences/bacteria_NC_010333.1.fasta.gz
                      sequences/bacteria_NC_017163.1.fasta.gz
                      sequences/bacteria_NC_017164.1.fasta.gz
                      sequences/bacteria_NC_017543.1.fasta.gz

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ganon-tests is a Catch v2.6.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
Scenario: Build
-------------------------------------------------------------------------------
/home/mi/fvangef/ganon/tests/ganon-build/GanonBuild.test.cpp:29
...............................................................................

/home/mi/fvangef/ganon/tests/ganon-build/GanonBuild.test.cpp:29: FAILED:
due to a fatal error condition:
  SIGFPE - Floating point error signal

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed

Gleitkomma-Ausnahme

**Comment by pirovc** [comment]
To run the tests please use the command `ctest -VV .` or do it from inside the data folder `../ganon-tests`

**Comment by fvangef** [comment]
Thank you, that works. 

I share my office with Enrico and he told me there is a way to automatically retrieve the taxonomy for new data, how do I do that?

**Comment by pirovc** [comment]
Ganon will always automatically retrieve the taxonomy for your sequences. Check it out the parametres `--seq-info` and `--taxdump-file` on ganon classify or more information on that. Please let me know if something is not clear.
