### ISSUE TITLE
Dealing with paired reads

### ISSUE THREAD

**Issue by mat43672** [pirovc/ganon#63]
Hi,

I see that ganon supports several fastq inputs, but no concept of paired reads, right? I am planning to fuse the reads with a "n" in the middle to break the k-mer prediction and be able to extract all k-mer for a pair... I think this works with other tools. Would that work with ganon, or I would end with chimeric k-mers overlapping the two pairs?

**Comment by pirovc** [comment]
Hi,

Indeed there's still no direct support for paired-end reads, but already on the plan for next releases.
The solution with one N between the pairs should be enough, it won't generate chimeric k-mers. Ganon uses SeqAn library dna5 type, which considers the N char as a real base. A k-mer with N won't match anywhere.

Just keep it in mind when using this solution that every read will have at least one error, so make sure the parameter `--max-error` is >= 1

Vitor

**Comment by mat43672** [comment]
Ok I will test this then. Thanks

**Comment by pirovc** [comment]
Implemented #103
