### ISSUE TITLE
.out files get too huge

### ISSUE THREAD

**Issue by margeti** [pirovc/ganon#85]
Hi,
I try to classify some reads using ganon and everytime the server runs out of memory at some point. It just produces a ridiculously big *.out file (>300GB) although the input file is only 10G, and because the server runs out of memory it never produces the other outfiles. Although I run it on really fat node on a HPC with 450G memory. Do you have any idea what could cause this problem?

This is the command I use:
ganon classify --ganon-path /path/to/ganon/ganon/0.1.2/bin/ --db-prefix my_db --reads /path/to/my/reads.fq -o /output/file -k species

**Comment by pirovc** [comment]
Hi,

I would suggest you to update to the most recent version (v0.1.4). The new code does not keep the output in the main memory. However it's still written on the disk. This file contains the mapping of your reads against the references and if it is too big it means that your sequences are matching everywhere. For that you should make the error parameters more stringent (lower `--max-error` OR higher `--min-kmers`).

I would also suggest to use threads `-t` (it really speed up things in ganon) and leave `-k` empty or use the full lineage up to species `-k superkingdom phylum class order family genus species` that way you have a better report file and can still get only the species results by filtering the file.

Best
Vitor

**Comment by margeti** [comment]
Thanks for the quick answer! Is there a parameter set which you would suggest for short reads (30-300bp) ?

**Comment by pirovc** [comment]
If you have unequal read sizes I would recommend to use `--min-kmers` instead of `--max-error`. You can start with the default `0.25` (meaning a quarter of the k-mers in your read should have a match to be considered) and if that still generates too many results, increase by a factor of 0.05.
