### ISSUE TITLE
no pylca in ganon v4 clone

### ISSUE THREAD

**Issue by margeti** [pirovc/ganon#86]
Hi, 
I tried to install ganon 4 but it always gives me an error 
"LCA module not found (pylca)"
The error message is triggered by the line
from pylca.pylca import LCA
However I can't find any pylca* in my ganon clone... 
Do you know how to solve this problem?

Thanks a lot!

**Comment by pirovc** [comment]
Hi @margeti ,

To install pylca you can clone it and install it as follows:

```
git clone https://github.com/pirovc/pylca.git
cd pylca
python3 setup.py install
python3 -c 'from pylca.pylca import *; unittest.main();' # test command
```
or use the conda installation:

```
conda install -c bioconda pylca
```

obs: all dependencies are automatically installed when using ganon via conda `conda install -c bioconda ganon`

Best
Vitor
