### ISSUE TITLE
ganon.db.filter file is huge 

### ISSUE THREAD

**Issue by agakrawczyk** [pirovc/ganon#87]
Hello, 
I try to build a database for ganon containing only human reference genome and the RVDB virus database. The command I use is just like in the tutorial:
ganon build --db-prefix ganon_viruses_db --input-files clean5.U-RVDB16_human.fasta 
I end up with having huge ganon_viruses_db.filter file, which is 159G, when the fasta files I used for builing it clean5.U-RVDB16_human.fasta take only 7.8G of space. Is this expected or I'm doing something wrong to end up with such a huge file? 
20K Sep 25 10:18 ganon_viruses_db.bins
159G Sep 25 11:24 ganon_viruses_db.filter
4.0K Sep 25 10:18 ganon_viruses_db.map
1.8K Sep 25 11:25 ganon_viruses_db.nodes
Best regards, 
Aga

**Comment by pirovc** [comment]
Hello Aga,

Try to put a limit to the filter size with the parameter `--max-bloom-size`. For example: `--max-bloom-size 32000` would limit the size of the filter to 32GB.

Ganon tries to estimate the best parameters to generate the filter. I'm guessing you have few very large sequences (human ref) and many small (viruses).  In this case ganon may be overestimating the necessary filter size to fit all sequences. The recommended solution would be to generate 2 separated databases, one for human and the other for viruses, so you can have it optimized. When classifying, you just have to tell ganon to use both databases: `ganon classify -d ganon_human_db ganon_viruses_db ...`, for example.

Best
Vitor

**Comment by agakrawczyk** [comment]
Thank you Vitor for such a quick answer and help! I have set the --max-bloom-size and it worked :) I will try later also to create two separate databases like you suggested. 
Best, 
Aga
