### ISSUE TITLE
ganon-build (core dumped)

### ISSUE THREAD

**Issue by idfarbanecha** [pirovc/ganon#88]
Hello, 

I would like to index all of refseq bacteria,archea,viral and human with ganon-build. 

I downloaded all the files with genome_updater.sh with the following command: 

```bash
genome_updater.sh -d "refseq" -g "archaea,bacteria,viral,human" -o path/to/DB -t 12 -b refseq -f "genomic.fna.gz,assembly_report.txt" -m -u -r -p
```

For indexing the downloaded files I used the following command:

```bash
ganon-build -e path/to/DB/refseq/acc_len_taxid_assembly.txt -o path/to/DB/refseq/refseq_db.filter -s 70000 -n 3 -k 19 -t 60 --verbose path/to/DB/refseq/files/*.fna.gz
```
At first I get a an Argument list too long error, so I concatenated all fna.gz into one file called refseq.fna.gz and retried the command.

I get the following error:

```bash
--seqid-bin-file      path/to/DB/refseq/acc_len_taxid_assembly.txt
--output-filter-file  path/to/DB/refseq/refseq_db.filter
--filter-size         70000
--filter-size-bits    3087007744
--hash-functions      3
--kmer-size           19
--n-batches           1000
--n-refs              400
--threads             60
--update-filter-file
--update-complete     0
--verbose             1
--reference-files
                     path/to/DB/refseq/refseq.fna.gz

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul
/bin/bash: line 1: 14186 Aborted                 (core dumped) ganon-build -e path/to/DB/refseq/acc_len_taxid_assembly.txt -o path/to/DB/refseq/refseq_db.filter -s 70000 -n 3 -k 19 -t 60 --verbose path/to/DB/refseq/refseq.fna.gz
```
Any suggestions on how to debug and fix this ?

**Comment by pirovc** [comment]
Hello,

Please check it out the ganon build command (instead of ganon-build). There
are some steps you are missing because you are trying to use the core
executable directly.

Best
Vitor

idfarbanecha <notifications@github.com> schrieb am Fr., 4. Okt. 2019, 11:40:

**Comment by idfarbanecha** [comment]
Hello, 
Thank you for your answer. Indexing works when using ganon build. 
I had to index viral, human and bacterial fna.gz files seperately in order for it to work.
