### ISSUE TITLE
Is it possible to memory-map a ganon db?

### ISSUE THREAD

**Issue by sujaikumar** [pirovc/ganon#92]
Is it possible to pre-load the ganon db into memory. Kraken recommends (https://ccb.jhu.edu/software/kraken/MANUAL.html#memory-usage-and-efficiency) creating a ramdisk and copying the kraken db to that. But would such an approach work for ganon as well?

**Comment by pirovc** [comment]
Hi @sujaikumar 

Yes, that works also with ganon. It will speed-up the index loading but won't affect classification speed.

Best
Vitor

**Comment by sujaikumar** [comment]
Many thanks for the prompt response!
