### ISSUE TITLE
Building database of all RefSeq bacteria, archaea, fungi and viruses

### ISSUE THREAD

**Issue by dparks1134** [pirovc/ganon#94]
Hi. I'm keen to give ganon a try, but a little unclear at how to build an initial database. Is there a script or recommend way to build a ganon database that covers all RefSeq bacteria, archaea, fungi and viruses? I'd like to build the RefSeq-ALL and/or RefSeq-ALL-top-3 database as described in the ganon bioRxiv manuscript. Alternatively, are there pre-built RefSeq databases available (I appreciate this sort of defeats the purposes of ganon)? Thanks.

**Comment by pirovc** [comment]
Hi @dparks1134 

To recreate the same databases used in the manuscript please follow the instructions on: https://github.com/pirovc/ganon_benchmark

Ganon works well with the genome_updater to download sequence files. More information here: https://github.com/pirovc/genome_updater

There are more detailed information on how to use ganon with genome_updater on the next version of the tool I am working on: https://github.com/pirovc/ganon/blob/dev/README.md

Please let me know if something is not clear of if you need some help figuring out the output/files.

Best
Vitor

**Comment by dparks1134** [comment]
Thanks! This is perfect.
