### ISSUE TITLE
ganon build results in Argument list too long

### ISSUE THREAD

**Issue by dparks1134** [pirovc/ganon#96]
Hi,

I'm trying to build a Ganon database with something like:
`ganon build --db-prefix sample_bacteria --input-files tests/ganon-build/data/sequences/bacteria*.fasta.gz`

This results in a `Argument list too long` error. Is it possible to simply specify the directory containing all the genomes along with the desired extension?

Cheers,
Donovan

**Comment by pirovc** [comment]
Hi @dparks1134 

Indeed, that's a recurrent problem. I will implement this in the next release. For now I would suggest to merge the downloaded files into one with:

`find genome_updater_output/version/files/ -name *genomic.fna.gz -exec cat {} + > merged.genomic.fna.gz`

Best
Vitor

**Comment by dparks1134** [comment]
Thanks!

**Comment by pirovc** [comment]
Implemented #103

**Comment by jdwinkler-lanzatech** [comment]
Hi,

This command still fails on the latest conda version on miniconda3; here is the error output:

[list of genomic.fna.gz arguments goes here]

Error code: 0
Out:
Traceback (most recent call last):
  File "/opt/conda/envs/ganon_env/bin/ganon", line 420, in run
    stderr=subprocess.PIPE)
  File "/opt/conda/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/opt/conda/envs/ganon_env/bin/ganon-build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ganon_env/bin/ganon", line 1150, in <module>
    main()
  File "/opt/conda/envs/ganon_env/bin/ganon", line 267, in main
    stdout, stderr = run(run_ganon_build_cmd, print_stderr=True)
  File "/opt/conda/envs/ganon_env/bin/ganon", line 434, in run
    if stdout: print_log(stdout+"\n")
UnboundLocalError: local variable 'stdout' referenced before assignment

I would suggest writing a temp file with the absolute file paths to the genomic.fna.gz files and having ganon-build read from that as a permanent fix.

**Comment by pirovc** [comment]
@jdwinkler-lanzatech 

Thanks for reporting it. Could you send it the stderr output until the error and the command line used?

Vitor

**Comment by jdwinkler-lanzatech** [comment]
Sure, I'll try to do so.

Would you mind if I provided a docker image with my setup too? I eventually cat'ed the fna.gz files together like you suggested and moved to a machine with more memory to generate the database. I can email it to you if you are interested.

**Comment by advaitb** [comment]
@pirovc I still get the error even after using the `--input-directory` and `--input extension` option. Here is the command I ran:
 `./ganon build --db-prefix arbac --input-directory "/home/dbs/refseq/arbac/" --input-extension "genomic.fna.gz"`. Attached the terminal screenshot below

![Screen Shot 2020-02-12 at 7 39 08 PM](https://user-images.githubusercontent.com/13657575/74393337-6964bc80-4dcf-11ea-8493-e1663d62fb8f.png)

**Comment by pirovc** [comment]
@advaitb Thanks for reporting. There is indeed still a bug which is causing the issue. It will be fixed in the next release. The solution now is to merge your files into one.

Cheers
Vitor

**Comment by pirovc** [comment]
fixed #116
